<template><div><h1 id="指令列表" tabindex="-1"><a class="header-anchor" href="#指令列表" aria-hidden="true">#</a> 指令列表</h1>
<table>
<thead>
<tr>
<th>指令名称</th>
<th>功能</th>
<th>备注</th>
</tr>
</thead>
<tbody>
<tr>
<td>/afk</td>
<td>进入离开状态</td>
<td></td>
</tr>
<tr>
<td>/back</td>
<td>返回上一个地点</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/balance</td>
<td>查看你的余额</td>
<td></td>
</tr>
<tr>
<td>/baltop</td>
<td>查看余额排行榜</td>
<td></td>
</tr>
<tr>
<td>/ca mail</td>
<td>打开你的邮箱，你在全球市场下架的东西都会存放在这里</td>
<td></td>
</tr>
<tr>
<td>/ca sell &lt;价格&gt; &lt;数量&gt;</td>
<td>将你手上的物品以一定的价格上架到全球市场</td>
<td></td>
</tr>
<tr>
<td>/home</td>
<td>回家</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/homes</td>
<td>查看家列表</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/msg</td>
<td>给某位玩家发送私聊</td>
<td></td>
</tr>
<tr>
<td>/ping</td>
<td>查看你的延迟</td>
<td></td>
</tr>
<tr>
<td>/playtime</td>
<td>查看你的在线时长</td>
<td></td>
</tr>
<tr>
<td>/playtimetop</td>
<td>查看服务器在线时长排行榜</td>
<td></td>
</tr>
<tr>
<td>/removehome</td>
<td>删除家</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/res help</td>
<td>获取领地插件的帮助</td>
<td></td>
</tr>
<tr>
<td>/sell</td>
<td>卖出物品获得余额</td>
<td></td>
</tr>
<tr>
<td>/sethome &lt;名字&gt;</td>
<td>设置一个家</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/shop</td>
<td>打开全球市场</td>
<td></td>
</tr>
<tr>
<td>/spawn</td>
<td>返回主城</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/tpa &lt;玩家ID&gt;</td>
<td>申请传送到某个玩家那</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/tpaccept</td>
<td>接受某个玩家的传送请求</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/tpahere &lt;玩家ID&gt;</td>
<td>请求其他玩家传送到自己这</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/tpdeny</td>
<td>拒绝某个玩家的传送请求</td>
<td>本指令目前可用，后续可能会删除，请勿过于依赖本指令</td>
</tr>
<tr>
<td>/worth</td>
<td>查询手上物品的出售价值</td>
<td></td>
</tr>
<tr>
<td>/worthlist</td>
<td>查询所有可出售物品的价值</td>
<td></td>
</tr>
</tbody>
</table>
</div></template>


